[package]
name = "metadata-integration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.3", features = ["derive"] }
roxmltree = "0.21"
anyhow = "1.0"
serde_json = { workspace = true }
busbar-sf-types = { path = "../sf-types", features = ["full"] }
